# tell travis we need cpy of docker running

sudo: required
services:
  - docker

before_install:
  - docker build -t jerryc96/react-test -f ./client/Dockerfile.dev ./client

# used to exec test suite
script:
  - docker run jerryc96/react-test npm test -- --coverage

# build production version of project
after_success:
  - docker build -t jerryc96/multi-docker-client ./client
  - docker build -t jerryc96/multi-docker-server ./server
  - docker build -t jerryc96/multi-docker-nginx ./nginx
  - docker build -t jerryc96/multi-docker-worker ./worker

# login to docker and push to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jerryc96/multi-docker-client
  - docker push jerryc96/multi-docker-server
  - docker push jerryc96/multi-docker-nginx
  - docker push jerryc96/multi-docker-worker
